//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUIDMSMobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUIDMSMobile.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepter.
        /// </summary>
        public static string Accepter {
            get {
                return ResourceManager.GetString("Accepter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse est requise.
        /// </summary>
        public static string AddressRequis {
            get {
                return ResourceManager.GetString("AddressRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout véhicule.
        /// </summary>
        public static string AjoutVéhicule {
            get {
                return ResourceManager.GetString("AjoutVéhicule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        public static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabe.
        /// </summary>
        public static string Arab {
            get {
                return ResourceManager.GetString("Arab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Attente de Validation.
        /// </summary>
        public static string AttenteValidation {
            get {
                return ResourceManager.GetString("AttenteValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez de compte ?.
        /// </summary>
        public static string AvoirCompte {
            get {
                return ResourceManager.GetString("AvoirCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue !.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendez-vous pris avec succès.
        /// </summary>
        public static string bookedok {
            get {
                return ResourceManager.GetString("bookedok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Carte Grise*.
        /// </summary>
        public static string CarteGrise {
            get {
                return ResourceManager.GetString("CarteGrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centre:.
        /// </summary>
        public static string Centre__ {
            get {
                return ResourceManager.GetString("Centre__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centres de service.
        /// </summary>
        public static string Centres__ {
            get {
                return ResourceManager.GetString("Centres__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du centre:.
        /// </summary>
        public static string Codecentre__ {
            get {
                return ResourceManager.GetString("Codecentre__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code du pack d&apos;entretien:.
        /// </summary>
        public static string Codepackentretien__ {
            get {
                return ResourceManager.GetString("Codepackentretien__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code postal est requis.
        /// </summary>
        public static string CodePostalRequis {
            get {
                return ResourceManager.GetString("CodePostalRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le compte a été créé avec succès.
        /// </summary>
        public static string comptesucces {
            get {
                return ResourceManager.GetString("comptesucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string Connecter {
            get {
                return ResourceManager.GetString("Connecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de compte.
        /// </summary>
        public static string CreationCompte {
            get {
                return ResourceManager.GetString("CreationCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une véhicule.
        /// </summary>
        public static string CreationVehicule {
            get {
                return ResourceManager.GetString("CreationVehicule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un compte.
        /// </summary>
        public static string CreerCompte {
            get {
                return ResourceManager.GetString("CreerCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les créneaux sélectionnés ne sont pas consécutifs ou insuffisants.
        /// </summary>
        public static string crenauxinf {
            get {
                return ResourceManager.GetString("crenauxinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les créneaux ou pack ne sont pas valides.
        /// </summary>
        public static string crenauxpasvalide {
            get {
                return ResourceManager.GetString("crenauxpasvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créneau.
        /// </summary>
        public static string Creneau {
            get {
                return ResourceManager.GetString("Creneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créneaux disponibles.
        /// </summary>
        public static string Creneauxd {
            get {
                return ResourceManager.GetString("Creneauxd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créneaux sélectionnés:.
        /// </summary>
        public static string Creneauxsel {
            get {
                return ResourceManager.GetString("Creneauxsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de mise en circulation *.
        /// </summary>
        public static string DateCirculation {
            get {
                return ResourceManager.GetString("DateCirculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de mise en circulation :.
        /// </summary>
        public static string DateCirculation__ {
            get {
                return ResourceManager.GetString("DateCirculation__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date et heure:.
        /// </summary>
        public static string DateHeure__ {
            get {
                return ResourceManager.GetString("DateHeure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date planifiée:.
        /// </summary>
        public static string Dateplanifie__ {
            get {
                return ResourceManager.GetString("Dateplanifie__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se deconnecter.
        /// </summary>
        public static string Deconnecter {
            get {
                return ResourceManager.GetString("Deconnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vous déconnecter ?.
        /// </summary>
        public static string DeconnecterPoPUp {
            get {
                return ResourceManager.GetString("DeconnecterPoPUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les détails du devis.
        /// </summary>
        public static string detaildevis {
            get {
                return ResourceManager.GetString("detaildevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Devis.
        /// </summary>
        public static string Devis {
            get {
                return ResourceManager.GetString("Devis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le devis a été accepté.
        /// </summary>
        public static string devisaccpte {
            get {
                return ResourceManager.GetString("devisaccpte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le devis a été refusé.
        /// </summary>
        public static string devisrefus {
            get {
                return ResourceManager.GetString("devisrefus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir tous les champs.
        /// </summary>
        public static string doitremplir {
            get {
                return ResourceManager.GetString("doitremplir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée (min):.
        /// </summary>
        public static string Dure__ {
            get {
                return ResourceManager.GetString("Dure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de connexion.
        /// </summary>
        public static string EchecConexion {
            get {
                return ResourceManager.GetString("EchecConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string Email_ {
            get {
                return ResourceManager.GetString("Email_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailInput {
            get {
                return ResourceManager.GetString("EmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse e-mail est requise.
        /// </summary>
        public static string EmailRequis {
            get {
                return ResourceManager.GetString("EmailRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En savoir plus.
        /// </summary>
        public static string Ensavoirplus {
            get {
                return ResourceManager.GetString("Ensavoirplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Votre compte est en attente de validation.
        /// </summary>
        public static string EreurAttendValidation {
            get {
                return ResourceManager.GetString("EreurAttendValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La photo de la carte grise est requise.
        /// </summary>
        public static string ereurcartegrise {
            get {
                return ResourceManager.GetString("ereurcartegrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Votre compte est bloqué.
        /// </summary>
        public static string EreurCompteBlock {
            get {
                return ResourceManager.GetString("EreurCompteBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Compte bloqué ou en attente de validation.
        /// </summary>
        public static string EreurCompteBlockeOuAttent {
            get {
                return ResourceManager.GetString("EreurCompteBlockeOuAttent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de mise en circulation est requise.
        /// </summary>
        public static string ereurdateimmatriculation {
            get {
                return ResourceManager.GetString("ereurdateimmatriculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Date de première immatriculation invalide..
        /// </summary>
        public static string EreurDateInvalide {
            get {
                return ResourceManager.GetString("EreurDateInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: utilisateur existe déjà.
        /// </summary>
        public static string EreurDejaexist {
            get {
                return ResourceManager.GetString("EreurDejaexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Erreur lors de l’envoi de l’email.
        /// </summary>
        public static string EreurEnvoieEmail {
            get {
                return ResourceManager.GetString("EreurEnvoieEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Genre invalide.
        /// </summary>
        public static string EreurGenre {
            get {
                return ResourceManager.GetString("EreurGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Numéro d&apos;immatriculation invalide..
        /// </summary>
        public static string EreurImatriculationinvalide {
            get {
                return ResourceManager.GetString("EreurImatriculationinvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;immatriculation est obligatoire..
        /// </summary>
        public static string ereurimtriculation {
            get {
                return ResourceManager.GetString("ereurimtriculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: inconnu.
        /// </summary>
        public static string EreurInconnu {
            get {
                return ResourceManager.GetString("EreurInconnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La marque est requise.
        /// </summary>
        public static string ereurmarque {
            get {
                return ResourceManager.GetString("ereurmarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Marque inconnue..
        /// </summary>
        public static string EreurMarqueInconnu {
            get {
                return ResourceManager.GetString("EreurMarqueInconnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le modèle est requis.
        /// </summary>
        public static string ereurmodel {
            get {
                return ResourceManager.GetString("ereurmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Modèle inconnu..
        /// </summary>
        public static string EreurModelInconnu {
            get {
                return ResourceManager.GetString("EreurModelInconnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Mot de passe incorrect.
        /// </summary>
        public static string EreurMpIncorect {
            get {
                return ResourceManager.GetString("EreurMpIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de châssis est requis.
        /// </summary>
        public static string ereurnchassis {
            get {
                return ResourceManager.GetString("ereurnchassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Numéro de châssis invalide..
        /// </summary>
        public static string EreurNumChasiinvalide {
            get {
                return ResourceManager.GetString("EreurNumChasiinvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Numéro de châssis déjà enregistré..
        /// </summary>
        public static string EreurNumChassiexiste {
            get {
                return ResourceManager.GetString("EreurNumChassiexiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Champs obligatoires manquants.
        /// </summary>
        public static string Ereurobilgatoire {
            get {
                return ResourceManager.GetString("Ereurobilgatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Photo de la carte d&apos;immatriculation invalide..
        /// </summary>
        public static string EreurPhoto {
            get {
                return ResourceManager.GetString("EreurPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue :.
        /// </summary>
        public static string Ereurservenue {
            get {
                return ResourceManager.GetString("Ereurservenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Utilisateur mobile invalide..
        /// </summary>
        public static string EreurUserInvalide {
            get {
                return ResourceManager.GetString("EreurUserInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Utilisateur introuvable.
        /// </summary>
        public static string EreurUserNonTrouvé {
            get {
                return ResourceManager.GetString("EreurUserNonTrouvé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string ErreurAllert {
            get {
                return ResourceManager.GetString("ErreurAllert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Francais {
            get {
                return ResourceManager.GetString("Francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le genre est requis.
        /// </summary>
        public static string GenderRequis {
            get {
                return ResourceManager.GetString("GenderRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heure planifiée:.
        /// </summary>
        public static string Heureplanifie__ {
            get {
                return ResourceManager.GetString("Heureplanifie__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string Historique {
            get {
                return ResourceManager.GetString("Historique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page de l’historique.
        /// </summary>
        public static string HistoriquePage {
            get {
                return ResourceManager.GetString("HistoriquePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page d&apos;accueil.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique des rendez-vous.
        /// </summary>
        public static string hrendezvous {
            get {
                return ResourceManager.GetString("hrendezvous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;identifiant est requis.
        /// </summary>
        public static string IdentifiantRequis {
            get {
                return ResourceManager.GetString("IdentifiantRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immatriculation *.
        /// </summary>
        public static string Immatriculation {
            get {
                return ResourceManager.GetString("Immatriculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immatriculation:.
        /// </summary>
        public static string Immatriculation__ {
            get {
                return ResourceManager.GetString("Immatriculation__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string Inscrire {
            get {
                return ResourceManager.GetString("Inscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        public static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilométrage:.
        /// </summary>
        public static string Kilométrage {
            get {
                return ResourceManager.GetString("Kilométrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilométrage.
        /// </summary>
        public static string Kilometrage__ {
            get {
                return ResourceManager.GetString("Kilometrage__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La langue est requise.
        /// </summary>
        public static string LanguageRequis {
            get {
                return ResourceManager.GetString("LanguageRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque *.
        /// </summary>
        public static string Marque {
            get {
                return ResourceManager.GetString("Marque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marque:.
        /// </summary>
        public static string Marque__ {
            get {
                return ResourceManager.GetString("Marque__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes véhicules.
        /// </summary>
        public static string MenuVehicule {
            get {
                return ResourceManager.GetString("MenuVehicule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page des rendez-vous.
        /// </summary>
        public static string MesRendezVousPage {
            get {
                return ResourceManager.GetString("MesRendezVousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string messageok {
            get {
                return ResourceManager.GetString("messageok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page des véhicules.
        /// </summary>
        public static string Mesvehicule {
            get {
                return ResourceManager.GetString("Mesvehicule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour réussie.
        /// </summary>
        public static string MiseAjourOk {
            get {
                return ResourceManager.GetString("MiseAjourOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise a jour de compte.
        /// </summary>
        public static string MiseCompte {
            get {
                return ResourceManager.GetString("MiseCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mise a jour.
        /// </summary>
        public static string MiseJour {
            get {
                return ResourceManager.GetString("MiseJour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle *.
        /// </summary>
        public static string Modele {
            get {
                return ResourceManager.GetString("Modele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle:.
        /// </summary>
        public static string Modle__ {
            get {
                return ResourceManager.GetString("Modle__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon compte.
        /// </summary>
        public static string MonCompte {
            get {
                return ResourceManager.GetString("MonCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant:.
        /// </summary>
        public static string Montant {
            get {
                return ResourceManager.GetString("Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Mp {
            get {
                return ResourceManager.GetString("Mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string MpOublie {
            get {
                return ResourceManager.GetString("MpOublie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe est requis.
        /// </summary>
        public static string MpRequis {
            get {
                return ResourceManager.GetString("MpRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro Devis:.
        /// </summary>
        public static string ndevis__ {
            get {
                return ResourceManager.GetString("ndevis__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du centre:.
        /// </summary>
        public static string Nomcentre__ {
            get {
                return ResourceManager.GetString("Nomcentre__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom est requis.
        /// </summary>
        public static string NomRequis {
            get {
                return ResourceManager.GetString("NomRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuméroChâssis:.
        /// </summary>
        public static string Numchass__ {
            get {
                return ResourceManager.GetString("Numchass__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de Châssis *.
        /// </summary>
        public static string Numerochassis {
            get {
                return ResourceManager.GetString("Numerochassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du créneau:.
        /// </summary>
        public static string Numrocrneau__ {
            get {
                return ResourceManager.GetString("Numrocrneau__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro WhatsApp est requis.
        /// </summary>
        public static string numWhatsApp {
            get {
                return ResourceManager.GetString("numWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack d&apos;entretien:.
        /// </summary>
        public static string PackEntretien__ {
            get {
                return ResourceManager.GetString("PackEntretien__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les créneaux sélectionnés ne sont pas consécutifs ou doivent exactement couvrir la durée du pack..
        /// </summary>
        public static string packinsufisant {
            get {
                return ResourceManager.GetString("packinsufisant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packs de maintenance:.
        /// </summary>
        public static string Packsmaintenance__ {
            get {
                return ResourceManager.GetString("Packsmaintenance__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page de création de compte.
        /// </summary>
        public static string pageCreationCompte {
            get {
                return ResourceManager.GetString("pageCreationCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page de devis.
        /// </summary>
        public static string pagedevis {
            get {
                return ResourceManager.GetString("pagedevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas de compte ?.
        /// </summary>
        public static string PasCompte {
            get {
                return ResourceManager.GetString("PasCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de connexion internet. Veuillez vérifier votre connexion et réessayer..
        /// </summary>
        public static string PasConexion {
            get {
                return ResourceManager.GetString("PasConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le pays est requis.
        /// </summary>
        public static string PaysRequis {
            get {
                return ResourceManager.GetString("PaysRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo 2.
        /// </summary>
        public static string Photo2 {
            get {
                return ResourceManager.GetString("Photo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo 3.
        /// </summary>
        public static string Photo3 {
            get {
                return ResourceManager.GetString("Photo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom est requis.
        /// </summary>
        public static string PrenomRequis {
            get {
                return ResourceManager.GetString("PrenomRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La prise de rendez-vous a échoué.
        /// </summary>
        public static string rdzechoue {
            get {
                return ResourceManager.GetString("rdzechoue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuser.
        /// </summary>
        public static string Refuser {
            get {
                return ResourceManager.GetString("Refuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser le mot de passe.
        /// </summary>
        public static string Réinitialiser {
            get {
                return ResourceManager.GetString("Réinitialiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes rendez-vous.
        /// </summary>
        public static string RendezVous {
            get {
                return ResourceManager.GetString("RendezVous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation réussie.
        /// </summary>
        public static string RenitialisationOk {
            get {
                return ResourceManager.GetString("RenitialisationOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rénitialiser.
        /// </summary>
        public static string Renitialise {
            get {
                return ResourceManager.GetString("Renitialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver.
        /// </summary>
        public static string Rserver {
            get {
                return ResourceManager.GetString("Rserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver un rendez-vous.
        /// </summary>
        public static string Rserverrdv {
            get {
                return ResourceManager.GetString("Rserverrdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un centre de service.
        /// </summary>
        public static string scentre {
            get {
                return ResourceManager.GetString("scentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner les créneaux disponibles.
        /// </summary>
        public static string screnaux {
            get {
                return ResourceManager.GetString("screnaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rester connecté.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir kilométrage.
        /// </summary>
        public static string sKilomtrage {
            get {
                return ResourceManager.GetString("sKilomtrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre route, en toute sérénité..
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un pack d&apos;entretien.
        /// </summary>
        public static string spack {
            get {
                return ResourceManager.GetString("spack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut:.
        /// </summary>
        public static string Statut__ {
            get {
                return ResourceManager.GetString("Statut__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Globalization;.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using LocalizationResourceManager.Maui; // ✅ Le bon package de JorgeFraga.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch (Exception ex).
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw ex;.
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static void SetAppLanguage(string lang, ILocalizationResourceManager localizationResourceManager).
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try.
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static class StaticMultiLang.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (lang).
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;fr&quot;:.
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;FR&quot;:.
        /// </summary>
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localizationResourceManager.CurrentCulture = new CultureInfo(&quot;fr&quot;);.
        /// </summary>
        public static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMLFlowDirection(FlowDirection.LeftToRight);.
        /// </summary>
        public static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLHorizontalTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetHorizontalOption(LayoutOptions.Start, LayoutOptions.StartAndExpand);.
        /// </summary>
        public static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLAllPickersImageAlign(ImageAlignment.Right);.
        /// </summary>
        public static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break;.
        /// </summary>
        public static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;en&quot;:.
        /// </summary>
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;EN&quot;:.
        /// </summary>
        public static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localizationResourceManager.CurrentCulture = new CultureInfo(&quot;en&quot;);.
        /// </summary>
        public static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMLFlowDirection(FlowDirection.LeftToRight);.
        /// </summary>
        public static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLHorizontalTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetHorizontalOption(LayoutOptions.Start, LayoutOptions.StartAndExpand);.
        /// </summary>
        public static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLAllPickersImageAlign(ImageAlignment.Right);.
        /// </summary>
        public static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break;.
        /// </summary>
        public static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static FlowDirection MLFlowDirection = FlowDirection.LeftToRight;.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;ar&quot;:.
        /// </summary>
        public static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;AR&quot;:.
        /// </summary>
        public static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localizationResourceManager.CurrentCulture = new CultureInfo(&quot;ar&quot;);.
        /// </summary>
        public static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMLFlowDirection(FlowDirection.RightToLeft);.
        /// </summary>
        public static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLTextAlign(TextAlignment.End);.
        /// </summary>
        public static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLHorizontalTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetHorizontalOption(LayoutOptions.End, LayoutOptions.EndAndExpand);.
        /// </summary>
        public static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLAllPickersImageAlign(ImageAlignment.Left);.
        /// </summary>
        public static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break;.
        /// </summary>
        public static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default: //français.
        /// </summary>
        public static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static void SetMLFlowDirection(FlowDirection flowDirection).
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localizationResourceManager.CurrentCulture = new CultureInfo(&quot;fr&quot;);.
        /// </summary>
        public static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetMLFlowDirection(FlowDirection.LeftToRight);.
        /// </summary>
        public static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLHorizontalTextAlign(TextAlignment.Start);.
        /// </summary>
        public static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetHorizontalOption(LayoutOptions.Start, LayoutOptions.StartAndExpand);.
        /// </summary>
        public static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //SetMLAllPickersImageAlign(ImageAlignment.Right);.
        /// </summary>
        public static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break;.
        /// </summary>
        public static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch (Exception ex).
        /// </summary>
        public static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw ex;.
        /// </summary>
        public static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLFlowDirection = flowDirection;.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string Succes {
            get {
                return ResourceManager.GetString("Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un véhicule.
        /// </summary>
        public static string svehicule {
            get {
                return ResourceManager.GetString("svehicule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour réussi.
        /// </summary>
        public static string Updateok {
            get {
                return ResourceManager.GetString("Updateok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Valider {
            get {
                return ResourceManager.GetString("Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véhicule créé avec succès.
        /// </summary>
        public static string VehiculeCreeSucces {
            get {
                return ResourceManager.GetString("VehiculeCreeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véhicules Validés.
        /// </summary>
        public static string VéhiculesValidés {
            get {
                return ResourceManager.GetString("VéhiculesValidés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ville est requise.
        /// </summary>
        public static string VilleRequis {
            get {
                return ResourceManager.GetString("VilleRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro WhatsApp.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
    }
}
